#!/bin/bash
# ------------------------------------------------------------------
# aidlc-contract — contract registry for multi-workstream (tier 3) delivery.
# ------------------------------------------------------------------
# Run in the HUB repository:
#   init                                        create the hub files (workstream map, registry, dependency map, contracts/)
#   workstream WS-001 --name Data --repo ../data-repo --owner "Helen T"
#   register C-001 --kind data --producer WS-001 --consumers WS-002,WS-004 --schema <path> --test "<cmd>" [--version 1.0.0]
#   request-approval C-001                       publish the approve-contract checkpoint (high risk) in the hub
#   approve C-001                                after the human decision: APPROVED (plain decision + green test)
#                                                or APPROVED_WITH_RISK (WITH RISK decision)
#   test [C-001|--all]                           run test_command in the producer repo: APPROVED→BREACHED on red,
#                                                APPROVED_WITH_RISK→APPROVED and BREACHED→APPROVED on green
#   regen                                        rebuild contract-registry.md and dependency-map.md
#   status
# Run in a CONSUMER repository (unit.yaml has hub: and consumes:):
#   check [--unit <unit.yaml>]                   exit 0 all approved · 3 building on risk-accepted contracts · 2 blocked
#   propose-lift [--unit <unit.yaml>]            when every consumed contract is APPROVED and the unit is excluded,
#                                                publish the lift-exclusion checkpoint (LIFT EXCLUSION: WS-NNN)
# ------------------------------------------------------------------
AIDLC_HOOK_NAME="aidlc-contract"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
. "$HERE/_lib/track-parse.sh"
. "$HERE/_lib/contracts.sh"
aidlc_require_jq
AIDLC_INPUT='{}'
CMD="$1"; shift
aidlc_load_state
T="$AIDLC_TRACK"; C="$T/contracts"
die() { echo "aidlc-contract: $*" >&2; exit 1; }
opt() { local k="$1"; shift; while [ $# -gt 0 ]; do [ "$1" = "$k" ] && { echo "$2"; return; }; shift; done; }

regen() {
  local reg="$T/contract-registry.md" dep="$T/dependency-map.md" f
  {
    echo "# Contract registry"
    echo ""
    echo "Generated by aidlc-contract.sh from contracts/C-NNN.md. Do not edit by hand."
    echo ""
    echo "| Contract | Kind | Producer | Consumers | Version | Status | Approved by | Last test |"
    echo "| --- | --- | --- | --- | --- | --- | --- | --- |"
    for f in "$C"/C-*.md; do [ -f "$f" ] || continue
      printf '| %s | %s | %s | %s | %s | %s | %s | %s |\n' "$(contract_field "$f" id)" "$(contract_field "$f" kind)" "$(contract_field "$f" producer)" \
        "$(contract_field "$f" consumers | tr -d '[]')" "$(contract_field "$f" version)" "$(contract_field "$f" status)" \
        "$(contract_field "$f" approved_by_decision)" "$(contract_field "$f" last_test)"
    done
  } > "$reg"
  {
    echo "# Dependency map"
    echo ""
    echo "Generated by aidlc-contract.sh from the workstream map and contracts. Do not edit by hand."
    echo ""
    echo '```mermaid'
    echo "flowchart LR"
    grep -E '^\| WS-[0-9]+' "$T/workstream-map.md" 2>/dev/null | awk -F'|' '{gsub(/ /,"",$2); n=$3; gsub(/^ +| +$/,"",n); printf "  %s[\"%s<br/>%s\"]\n", $2, $2, n}'
    for f in "$C"/C-*.md; do [ -f "$f" ] || continue
      local p="$(contract_field "$f" producer)" id="$(contract_field "$f" id)" st="$(contract_field "$f" status)" cons
      for cons in $(contract_field "$f" consumers | tr -d '[],'); do echo "  $p -- \"$id $st\" --> $cons"; done
    done
    echo '```'
  } > "$dep"
}

producer_repo() { # producer_repo <WS-NNN> → absolute path of the producer repository
  local r; r="$(grep -E "^\| $1 " "$T/workstream-map.md" 2>/dev/null | awk -F'|' '{gsub(/^ +| +$/,"",$4); print $4}')"
  [ -z "$r" ] && return 1
  case "$r" in /*) echo "$r" ;; *) (cd "$AIDLC_PROJECT/$r" 2>/dev/null && pwd) ;; esac
}

latest_contract_decision() { # latest_contract_decision <WS-NNN> → "HD-NNN <plain|risk>" from the hub decision log
  awk -v ws="$1" '
    /^### \[HD-[0-9]+\] APPROVE WORKSTREAM CONTRACT/ { id=$2; gsub(/[\[\]]/,"",id); kind=(index($0,"WITH RISK")?"risk":"plain"); ok=(index($0,": " ws)>0) ; next }
    ok && /\*\*Status:\*\* APPROVED/ { last=id " " kind; ok=0 }
    END { if (last!="") print last }' "$T/human-decisions.md" 2>/dev/null
}

run_test() { # run_test <contract file> → 0 green, 1 red, 2 no test
  local f="$1" cmd repo ws out
  cmd="$(contract_field "$f" test_command)"; ws="$(contract_field "$f" producer)"
  [ -z "$cmd" ] && return 2
  repo="$(producer_repo "$ws")" || { echo "  ! $ws has no repo in workstream-map.md" >&2; return 1; }
  out="$(cd "$repo" && bash -o pipefail -c "$cmd" 2>&1)"; local rc=$?
  contract_set_field "$f" last_test "$([ $rc -eq 0 ] && echo PASS || echo FAIL) $(aidlc_now)"
  aidlc_lineage "-" "contract.tested: $(contract_field "$f" id) $([ $rc -eq 0 ] && echo pass || echo fail)" "$(aidlc_rel "$f")" "$(aidlc_hash "$f")"
  [ $rc -eq 0 ] && return 0
  printf '%s\n' "$out" | tail -5 | sed 's/^/    /' >&2
  return 1
}

case "$CMD" in
  init)
    { [ -f "$HERE/../setup/init-track.sh" ] && (cd "$AIDLC_PROJECT" && bash "$HERE/../setup/init-track.sh" --hub >/dev/null 2>&1); } || {
      # installed copy: no setup/ next to hooks; create the hub files directly
      [ -f "$T/state.md" ] || die "no track root in $(aidlc_rel "$T"); run setup/init-track.sh --hub from sdlc_central"
      mkdir -p "$T/contracts"
      [ -f "$T/workstream-map.md" ] || printf '# Workstream map\n\n| Workstream | Name | Repo | Owner | Produces | Consumes |\n| --- | --- | --- | --- | --- | --- |\n' > "$T/workstream-map.md"
    }
    mkdir -p "$C"; regen; aidlc_lineage "-" "contract.hub_initialised: $(basename "$AIDLC_PROJECT")" "$(aidlc_rel "$T/workstream-map.md")" "-"
    echo "K00 hub ready at $(aidlc_rel "$T")" ;;

  workstream)
    WS="$1"; shift; printf '%s' "$WS" | grep -Eq '^WS-[0-9]+$' || die "usage: workstream WS-NNN --name <n> --repo <path> --owner <o>"
    [ -f "$T/workstream-map.md" ] || die "run init first"
    grep -q "^| $WS " "$T/workstream-map.md" && die "$WS already in workstream-map.md"
    printf '| %s | %s | %s | %s | | |\n' "$WS" "$(opt --name "$@")" "$(opt --repo "$@")" "$(opt --owner "$@")" >> "$T/workstream-map.md"
    regen; echo "K00 $WS added" ;;

  register)
    ID="$1"; shift; printf '%s' "$ID" | grep -Eq '^C-[0-9]+$' || die "usage: register C-NNN --kind ... --producer WS-NNN --consumers WS-..,WS-.. --schema <path> --test <cmd>"
    mkdir -p "$C"; F="$C/$ID.md"; [ -f "$F" ] && die "$ID already registered"
    PROD="$(opt --producer "$@")"; CONS="$(opt --consumers "$@" | tr ',' ' ')"
    grep -q "^| $PROD " "$T/workstream-map.md" 2>/dev/null || die "producer $PROD is not in workstream-map.md"
    cat > "$F" <<EOF
---
id: $ID
kind: $(opt --kind "$@")
producer: $PROD
consumers: [$(printf '%s' "$CONS" | sed 's/ /, /g')]
schema: $(opt --schema "$@")
test_command: "$(opt --test "$@")"
version: $(v="$(opt --version "$@")"; echo "${v:-1.0.0}")
status: DRAFT
approved_by_decision:
last_test:
---
# $ID

$(opt --description "$@")
EOF
    # keep the workstream map's produces / consumes columns current
    TMP="$(mktemp)"; awk -F'|' -v OFS='|' -v p="$PROD" -v c=" $CONS " -v id="$ID" '
      /^\| WS-[0-9]+/ { ws=$2; gsub(/ /,"",ws)
        if (ws==p) { v=$6; gsub(/^ +| +$/,"",v); $6=" " (v==""?id:v ", " id) " " }
        if (index(c, " " ws " ")) { v=$7; gsub(/^ +| +$/,"",v); $7=" " (v==""?id:v ", " id) " " } }
      {print}' "$T/workstream-map.md" > "$TMP" && cat "$TMP" > "$T/workstream-map.md"; rm -f "$TMP"
    regen; aidlc_lineage "-" "contract.registered: $ID DRAFT" "$(aidlc_rel "$F")" "$(aidlc_hash "$F")"
    echo "K00 $ID registered as DRAFT" ;;

  request-approval)
    ID="$1"; F="$C/$ID.md"; [ -f "$F" ] || die "$ID not registered"
    set_resume_field "$AIDLC_STATE" BLOCKED_GATE approve-contract
    set_resume_field "$AIDLC_STATE" GATE_RISK high
    set_resume_field "$AIDLC_STATE" NEXT_ACTION "Decide $ID: APPROVE WORKSTREAM CONTRACT: $(contract_field "$F" producer) - <acknowledgement> | APPROVE WORKSTREAM CONTRACT WITH RISK: $(contract_field "$F" producer) - <risk and excluded scope> | REQUEST CHANGES: <reason>"
    set_resume_field "$AIDLC_STATE" NEXT_ACTION_OWNER "human:architect"
    set_resume_field "$AIDLC_STATE" NEXT_ACTION_INPUTS "$(aidlc_rel "$F")"
    aidlc_lineage "-" "decision.checkpoint_published: approve-contract" "$(aidlc_rel "$F")" "$(aidlc_hash "$F")"
    echo "## AIDLC CHECKPOINT REQUIRED"; echo "Gate: approve-contract   Risk: high   Contract: $ID"; resume_field "$AIDLC_STATE" NEXT_ACTION ;;

  approve)
    ID="$1"; F="$C/$ID.md"; [ -f "$F" ] || die "$ID not registered"
    PROD="$(contract_field "$F" producer)"
    DEC="$(latest_contract_decision "$PROD")"
    [ -z "$DEC" ] && { echo "K01 $ID: no accepted APPROVE WORKSTREAM CONTRACT decision for $PROD in the hub decision log. Run request-approval $ID and have the architect decide." >&2; exit 2; }
    HD="${DEC%% *}"; KIND="${DEC#* }"
    if [ "$KIND" = "risk" ]; then
      contract_set_field "$F" status APPROVED_WITH_RISK; contract_set_field "$F" approved_by_decision "$HD"
      regen; aidlc_lineage "$HD" "contract.approved_with_risk: $ID" "$(aidlc_rel "$F")" "$(aidlc_hash "$F")"
      echo "K00 $ID APPROVED_WITH_RISK by $HD: consumers may build; their release claims are excluded until $ID is verified"
    else
      run_test "$F"; R=$?
      if [ $R -ne 0 ]; then echo "K02 $ID: decision $HD found but the contract test is $([ $R -eq 2 ] && echo missing || echo red); status stays $(contract_field "$F" status)" >&2; exit 2; fi
      contract_set_field "$F" status APPROVED; contract_set_field "$F" approved_by_decision "$HD"
      regen; aidlc_lineage "$HD" "contract.approved: $ID" "$(aidlc_rel "$F")" "$(aidlc_hash "$F")"
      echo "K00 $ID APPROVED by $HD with a green contract test"
    fi ;;

  test)
    TARGETS="$1"; [ "$TARGETS" = "--all" ] || [ -z "$TARGETS" ] && TARGETS="$(ls "$C"/C-*.md 2>/dev/null | xargs -n1 basename 2>/dev/null | sed 's/\.md$//')"
    RC=0
    for ID in $TARGETS; do F="$C/$ID.md"; [ -f "$F" ] || continue
      ST="$(contract_field "$F" status)"
      case "$ST" in APPROVED|APPROVED_WITH_RISK|BREACHED) ;; *) echo "  ○ $ID $ST (not tested until approved)"; continue ;; esac
      run_test "$F"; R=$?
      if [ $R -eq 0 ]; then
        case "$ST" in
          APPROVED_WITH_RISK) contract_set_field "$F" status APPROVED; aidlc_lineage "-" "contract.verified: $ID" "$(aidlc_rel "$F")" "$(aidlc_hash "$F")"
            echo "  ✓ $ID verified: APPROVED_WITH_RISK -> APPROVED. Consumers can now propose LIFT EXCLUSION." ;;
          BREACHED) contract_set_field "$F" status APPROVED; aidlc_lineage "-" "contract.restored: $ID" "$(aidlc_rel "$F")" "$(aidlc_hash "$F")"; echo "  ✓ $ID restored: BREACHED -> APPROVED" ;;
          *) echo "  ✓ $ID green" ;;
        esac
      else
        if [ "$ST" = "APPROVED" ]; then contract_set_field "$F" status BREACHED; aidlc_lineage "-" "contract.breached: $ID" "$(aidlc_rel "$F")" "$(aidlc_hash "$F")"
          echo "  ✗ $ID BREACHED: the producer no longer meets the approved contract; consumers are blocked"; RC=2
        else echo "  ✗ $ID red ($ST)"; RC=2; fi
      fi
    done
    regen; exit $RC ;;

  regen) regen; echo "K00 registry and dependency map regenerated" ;;

  status) sed -n '/^| Contract/,$p' "$T/contract-registry.md" 2>/dev/null ;;

  check)
    U="$(opt --unit "$@")"; [ -z "$U" ] && U="$AIDLC_PHASE_DIR/unit.yaml"
    [ -f "$U" ] || die "no unit.yaml ($U)"
    contract_check_unit "$U"; R=$?
    [ $R -eq 3 ] && unit_set_excluded "$U" true
    exit $R ;;

  propose-lift)
    U="$(opt --unit "$@")"; [ -z "$U" ] && U="$AIDLC_PHASE_DIR/unit.yaml"
    grep -q '^release_claims_excluded:[[:space:]]*true' "$U" 2>/dev/null || { echo "K00 unit is not excluded; nothing to lift"; exit 0; }
    OUT="$(contract_check_unit "$U")"; R=$?
    [ $R -ne 0 ] && { echo "K03 not yet: $(printf '%s' "$OUT" | grep -v '^OK' | tr '\n' ';')" >&2; exit 2; }
    WS="$(grep -E '^workstream:' "$U" | grep -Eo 'WS-[0-9]+')"; WS="${WS:-WS-NNN}"
    set_resume_field "$AIDLC_STATE" BLOCKED_GATE lift-exclusion
    set_resume_field "$AIDLC_STATE" GATE_RISK high
    set_resume_field "$AIDLC_STATE" NEXT_ACTION "Every consumed contract is APPROVED. Reply LIFT EXCLUSION: $WS - <acknowledgement> to restore release claims"
    set_resume_field "$AIDLC_STATE" NEXT_ACTION_OWNER "human:architect"
    set_resume_field "$AIDLC_STATE" NEXT_ACTION_INPUTS "$(aidlc_rel "$U")"
    aidlc_lineage "-" "decision.checkpoint_published: lift-exclusion" "$(aidlc_rel "$U")" "$(aidlc_hash "$U")"
    echo "## AIDLC CHECKPOINT REQUIRED"; echo "Gate: lift-exclusion   Risk: high"; resume_field "$AIDLC_STATE" NEXT_ACTION ;;

  *) sed -n '2,24p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 64 ;;
esac
