#!/bin/bash
# aidlc-artifact-hygiene — runs after a write to the track root or docs/aidlc/.
# Blocks secrets, raw context wrappers, unresolved markers in approved artifacts,
# and hand-written evidence. Also usable directly: --all scans every artifact.
AIDLC_HOOK_NAME="aidlc-artifact-hygiene"
. "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/_lib/track-parse.sh"
aidlc_require_jq

if [ "$1" = "--all" ]; then AIDLC_INPUT='{}'; else aidlc_read_input; fi
aidlc_load_state
aidlc_active || exit 0
TRACK_REL="$(aidlc_rel "$AIDLC_TRACK")"

# Is this artifact referenced by an accepted decision in lineage?
approved() {
  local rel="$1"
  [ -f "$AIDLC_TRACK/lineage.md" ] || return 1
  grep -F "$rel" "$AIDLC_TRACK/lineage.md" | grep -Eq 'decision\.accepted|APPROVED'
}

scan_file() {
  local abs="$1" rel
  rel="$(aidlc_rel "$abs")"
  [ -f "$abs" ] || return 0
  case "$rel" in
    "$TRACK_REL"/*|docs/aidlc/*) ;;
    *) return 0 ;;
  esac
  case "$rel" in *.md|*.yaml|*.yml|*.json|*.txt) ;; *) return 0 ;; esac
  # The guardrail log quotes blocked input by design.
  case "$rel" in "$TRACK_REL"/guardrail-log.md) return 0 ;; esac

  if grep -Eq "$AIDLC_SECRET_RE" "$abs"; then
    aidlc_block H01 "secret pattern in $rel (line $(grep -En "$AIDLC_SECRET_RE" "$abs" | head -1 | cut -d: -f1))" \
      "remove the secret, rotate it, and reference it from the environment"
  fi
  if grep -Eq "$AIDLC_WRAPPER_RE" "$abs"; then
    aidlc_block H02 "raw context wrapper in $rel (line $(grep -En "$AIDLC_WRAPPER_RE" "$abs" | head -1 | cut -d: -f1))" \
      "rewrite the artifact as plain content; quote pulled text instead of pasting prompt wrappers"
  fi
  if approved "$rel" && grep -Eq '(^|[^A-Za-z])(TBD|TODO|FIXME)([^A-Za-z]|$)' "$abs"; then
    aidlc_block H03 "unresolved TBD/TODO in approved artifact $rel" \
      "resolve the marker, or raise REQUEST CHANGES on the gate that approved it"
  fi
  case "$(basename "$rel")" in
    VERIFICATION.md|UAT.md|CONTRACT_EVIDENCE.md)
      if ! grep -q 'generated-by: aidlc-evidence-verifier' "$abs"; then
        aidlc_block H05 "$rel was not generated by aidlc-evidence-verifier" \
          "delete it and run the verification step; evidence is generated, never authored"
      fi ;;
  esac
}

if [ "$1" = "--all" ]; then
  find "$AIDLC_TRACK" "$AIDLC_PROJECT/docs/aidlc" -type f 2>/dev/null | while read -r f; do
    ( AIDLC_INPUT='{}'; scan_file "$f" ) || exit $?
  done
  exit $?
fi

TARGET="$(aidlc_field .path)"
[ -z "$TARGET" ] && exit 0
scan_file "$(aidlc_abs "$TARGET")"
exit 0
