#!/usr/bin/env python3
"""Write a SAMPLE track root for the Measurement Bench demo and UI tests.

Usage: python3 tests/fixtures/make-sample-track.py <project-dir> <squad-name> [--seed N] [--units N]

Every file is in the exact format the real hooks and tools write (lineage, human-decisions,
evidence index, VERIFICATION summary lines, gate-history, guardrail-log, usage, incidents,
baseline), with timestamps spread over past months so lead times are meaningful. The real
aidlc-metrics.sh then computes everything from these files. The track carries a SAMPLE marker,
so metrics.json and every view built from it say "sample data". Never use it as evidence.
"""
import json, os, random, subprocess, sys
from datetime import datetime, timedelta, timezone

args = sys.argv[1:]
if len(args) < 2: sys.exit(__doc__)
proj, squad = args[0], args[1]
seed = int(args[args.index('--seed') + 1]) if '--seed' in args else 7
n_units = int(args[args.index('--units') + 1]) if '--units' in args else 10
rnd = random.Random(seed)
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

os.makedirs(proj, exist_ok=True)
subprocess.run(['git', 'init', '-q'], cwd=proj, check=True)
subprocess.run(['bash', os.path.join(ROOT, 'setup', 'init-track.sh')], cwd=proj, check=True, stdout=subprocess.DEVNULL)
os.makedirs(os.path.join(proj, '.claude', 'config'), exist_ok=True)
with open(os.path.join(proj, '.claude', 'sdlc-central.json'), 'w') as f: json.dump({'agent': 'claude-code', 'track_root': '.track', 'tier_default': 2}, f)
T = os.path.join(proj, '.track')
open(os.path.join(T, 'SAMPLE'), 'w').write('Generated by tests/fixtures/make-sample-track.py. Not real delivery data.\n')

iso = lambda d: d.strftime('%Y-%m-%dT%H:%M:%SZ')
lineage, hds, blocks, gates, incidents = [], [], [], [], []
usage = {}
hd_n = 0
start = datetime(2026, 3, 2, 9, 0, tzinfo=timezone.utc)
names = ['checkout-api', 'refund-flow', 'password-reset', 'audit-export', 'rate-limits', 'search-index', 'invoice-pdf',
         'sso-login', 'price-rules', 'cart-merge', 'order-events', 'fraud-score', 'tax-engine', 'webhooks']
t = start
for i in range(n_units):
    learn = max(0.6, 1.5 - i * 0.1)                     # early units are slower: the learning curve
    tier = 1 if rnd.random() < 0.2 else (3 if rnd.random() < 0.15 else 2)
    prof = 'bugfix' if tier == 1 else rnd.choice(['feature', 'feature', 'security', 'data'])
    p = '%02d-%s' % (i + 1, names[i % len(names)])
    d = os.path.join(T, 'phases', p); os.makedirs(os.path.join(d, 'evidence'), exist_ok=True)
    open(os.path.join(d, 'unit.yaml'), 'w').write('id: UOW-%03d\nname: %s\nprofile: %s\ntier: %d\n' % (i + 1, p[3:], prof, tier))
    art = '.track/phases/%s/unit.yaml' % p
    t += timedelta(days=rnd.uniform(3, 9))
    cur = t
    def ev(ref, what, artifact=art, when=None):
        lineage.append('%s | %s | %s | %s | sha256:- | model=sample | sdlc=2.0.0-alpha' % (iso(when or cur), ref, what, artifact))
    stages = [('intake', .3), ('spec', 1.5), ('design', 1.2), ('planning', 1.4), ('execution', 4.5), ('verification', 1.3), ('review', .8)]
    if tier == 1: stages = [('intake', .2), ('execution', 1.5), ('verification', .5)]
    gate_at = {'spec': 'approve-spec', 'planning': 'approve-plan', 'review': 'approve-release'}
    for st, base_days in stages:
        ev(p, 'stage.entered: ' + st)
        dur = base_days * learn * rnd.uniform(.7, 1.4) * (1.6 if tier == 3 else 1)
        cur += timedelta(days=dur)
        g = gate_at.get(st)
        if g and tier > 1:
            ev('-', 'decision.checkpoint_published: ' + g, '.track/phases/%s/SPEC.md' % p)
            if rnd.random() < 0.25 * learn:               # a vague reply refused first
                hds.append('- attempt refused: REJECTED (Code 403, A01)')
                blocks.append('| %s | aidlc-human-approval-guard | A01 | %s | vague approval |' % (iso(cur + timedelta(hours=2)), p))
            wait = rnd.uniform(1, 30) * (1.8 if g == 'approve-release' else 1)
            rework = rnd.random() < 0.2 * learn
            for status, ev_name in ([('CHANGES REQUESTED', 'decision.request_changes')] if rework else []) + [('APPROVED', 'decision.accepted')]:
                hd_n += 1; hd = 'HD-%03d' % hd_n
                cur += timedelta(hours=wait if status == 'APPROVED' and not rework else wait / 2)
                ident = 'github' if g == 'approve-release' and i > 3 else 'asserted'
                hds.append('### [%s] %s\n- **Decider:** sample (%s), identity: %s\n- **Gate:** `%s` · **Risk:** medium · **Phase:** `%s` · **Status:** %s\n' % (hd, g.upper(), 'role', ident, g, p, status))
                ev(hd, '%s: %s' % (ev_name, g), '.track/phases/%s/SPEC.md' % p)
                if status == 'CHANGES REQUESTED': ev('-', 'decision.checkpoint_published: ' + g, '.track/phases/%s/SPEC.md' % p)
        if st == 'execution':
            for _ in range(rnd.randint(0, 3)):
                code = rnd.choice(['W02', 'W02', 'W06', 'C01', 'T07', 'H03'])
                hook = {'W': 'aidlc-pre-write-guard', 'C': 'aidlc-pre-command-guard', 'T': 'aidlc-traceability-check', 'H': 'aidlc-artifact-hygiene'}[code[0]]
                blocks.append('| %s | %s | %s | %s | sample block |' % (iso(cur - timedelta(hours=rnd.uniform(1, 20))), hook, code, p))
    ev(p, 'stage.entered: released', '.track/phases/%s/SCORECARD.md' % p)
    # tasks, red/green evidence, verification summary
    n_tasks = 1 if tier == 1 else rnd.randint(3, 6)
    open(os.path.join(d, 'TASKS.md'), 'w').write(''.join('## TASK-%03d part %d\n- covers AC-%d\n- Verify: `npm test -- part%d`\n' % (k + 1, k + 1, k + 1, k + 1) for k in range(n_tasks)))
    entries, eid = [], 0
    for k in range(n_tasks):
        task = 'TASK-%03d' % (k + 1)
        if rnd.random() < min(0.95, 0.35 + i * 0.08):   # test-first adoption grows over time
            eid += 1; entries.append({'id': 'E-%03d' % eid, 'task': task, 'kind': 'test', 'exit_code': 1, 'expect': 'fail', 'command': 'npm test -- part%d' % (k + 1)})
        eid += 1; entries.append({'id': 'E-%03d' % eid, 'task': task, 'kind': 'test', 'exit_code': 0, 'command': 'npm test -- part%d' % (k + 1), 'stale': False})
    json.dump({'version': 1, 'entries': entries}, open(os.path.join(d, 'evidence', 'index.json'), 'w'))
    crit = n_tasks; passed = crit if rnd.random() > 0.1 else crit - 1
    open(os.path.join(d, 'VERIFICATION.md'), 'w').write('<!-- sample -->\n# VERIFICATION — %s\n\n## Summary\n- **Result:** %s\n- **Criteria:** %d pass, %d fail, of %d\n' % (p, 'COMPLETE' if passed == crit else 'FAILED', passed, crit - passed, crit))
    first_pass = rnd.random() < min(0.9, 0.4 + i * 0.06)
    gates.append({'type': 'release-scorecard', 'phase': p, 'date': iso(cur), 'decision': 'PASS' if first_pass else 'FAIL'})
    if not first_pass: gates.append({'type': 'release-scorecard', 'phase': p, 'date': iso(cur), 'decision': 'PASS'})
    if rnd.random() < 0.18 * learn: incidents.append({'phase': p, 'restore_hours': round(rnd.uniform(0.5, 9), 1)})
    tok = int({1: 60000, 2: 190000, 3: 360000}[tier] * rnd.uniform(0.7, 1.4))
    usage[p] = {'messages': tok // 4000, 'input': tok // 10, 'output': tok // 12, 'cache_read': tok - tok // 10 - tok // 12 - tok // 20, 'cache_creation': tok // 20}

with open(os.path.join(T, 'lineage.md'), 'a') as f: f.write('\n'.join(lineage) + '\n')
with open(os.path.join(T, 'human-decisions.md'), 'a') as f: f.write('\n' + '\n'.join(hds) + '\n')
with open(os.path.join(T, 'guardrail-log.md'), 'w') as f:
    f.write('# Guardrail log\n\n| Timestamp | Hook | Code | Phase | Detail |\n| --- | --- | --- | --- | --- |\n' + '\n'.join(sorted(blocks)) + '\n')
json.dump({'gates': gates}, open(os.path.join(T, 'gate-history.json'), 'w'))
json.dump({'incidents': incidents}, open(os.path.join(T, 'incidents.json'), 'w'))
json.dump({'recorded_at': '2026-02-27', 'source': 'sample: prior two quarters from the tracker', 'lead_time_days': round(rnd.uniform(16, 24), 1),
           'rework_rate': 0.28, 'change_failure_rate': 0.22, 'deployment_frequency_per_30d': 1.5}, open(os.path.join(T, 'baseline.json'), 'w'), indent=2)
os.makedirs(os.path.join(T, 'runs', 'usage'), exist_ok=True)
json.dump({'session': 'sample', 'agent': 'claude-code', 'by_phase': usage}, open(os.path.join(T, 'runs', 'usage', 'sample.json'), 'w'))
print('sample track for %s: %d units in %s' % (squad, n_units, T))
